### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by axello** [fortmarek/automata-editor#9]
Hi, 
how hard would it be to either
a) include the Xcode project to build the iPad app or
b) include build instructions if they're obviously different from Apple's default?

then more people can also easier sample your app e.g. in a simulator.

Not everyone, I would say 99% of iOS developers, is familiar with the `tuist` build system, so a teeny-tiny addition to the readme would help already!

When I did do a `tuist build` or clean, or run, it has all kinds of complaints of missing Info.plists in all the *.xcframeworks. Basically, all the xcframeworks are empty!
Hmm, `git-lfs` also needs to be installed.

Ah, and *then* comes the real culprit:
`This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.`

So, no luck trying your app out!

Cheers.

**Comment by fortmarek** [comment]
Hey @axello!

If you have `tuist` installed, you should be able to run `tuist generate` and then open the generated `.xcodeproj`. Afterwards, you can work with the project as you would have normally. 

I have paid the git lfs quota, I missed it ran out. Let me know if it works for you and if you have any questions or suggestions!

I plan to get back to this sometime soon as I would love to eventually release it on AppStore once I feel the quality is good enough.

**Comment by axello** [comment]
Oh man, github did not notify me, or I missed it that your answered so soon after my issue request. It just notified me you closed it.
I will have another go at your automata editor soon!

**Comment by fortmarek** [comment]
No worries! I am currently working on a UI overhaul in [this](https://github.com/fortmarek/automata-editor/tree/overview-page) branch, although not everything is working there. The goal is to achieve a similar experience as the Swift playgrounds but for automata 🤞
